### ISSUE TITLE
Why is there no AbstractStopCondition type ?

### ISSUE THREAD

**Issue by felixchalumeau** [JuliaReinforcementLearning/ReinforcementLearningCore.jl#74]
Hi, 
I was just wandering why there was an AbstractHook type but no AbstractStopCondition type. It might not be important at all as everything run perfectly and I have not build any use case where this would be an real issue but I am curious about this.

**Comment by findmyway** [comment]
Good catch 👍 

The `AbstractHook` only exists for convenience. Let's say we want to define a new hook. Since it will be called at different stages in the `run` function, so all the following methods **must** be defined:

https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/blob/master/src/core/hooks.jl#L17-L20

But if the hook is defined to be an `AbstractHook`, then you only need to define the behavior at the stages you are interested in. In other stages, the [default one](https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/blob/master/src/core/hooks.jl#L24) will be called (which just returns `nothing`).

As for `StopCondition`, since it will only be called in one place, there's no need to add an extra concept here.

**Comment by felixchalumeau** [comment]
Ok ! Got it ! 

Thank you very much !

**Comment by findmyway** [comment]
My pleasure. The document hasn't been updated for a while. Feel free to raise an issue if you have any questions.
